task3_orig: pth_ll_rwl/pth_ll_rwl.c
	mkdir -p build
	gcc -o build/task3_orig -Ipth_ll_rwl pth_ll_rwl/my_rand.c pth_ll_rwl/pth_ll_rwl.c -lpthread -O3

task3_custom: pth_ll_rwl/pth_ll_rwl_custom.c
	mkdir -p build
	gcc -o build/task3_custom -Ipth_ll_rwl pth_ll_rwl/my_rand.c pth_ll_rwl/pth_ll_rwl_custom.c -lpthread -O3
